# -*- coding: utf-8 -*-
"""Entrenamiento_Iteracion5v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vJ_jYy06Cxo4cBjYpU_CtY4WXnEleeQ6
"""

import hashlib
import os
import random
import subprocess
from collections import Counter, defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from PIL import Image, UnidentifiedImageError
import tensorflow as tf
from tensorflow.keras.preprocessing.image import ImageDataGenerator, img_to_array, load_img, save_img
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array
from tensorflow.keras.applications import MobileNetV2
from tensorflow.keras.models import Model, Sequential
from tensorflow.keras.layers import Dense, Flatten, Dropout, GlobalAveragePooling2D
from tensorflow.keras.optimizers import Adam
from sklearn.utils.class_weight import compute_class_weight
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np
import seaborn as sns
from google.colab import drive
from tensorflow.keras.applications import MobileNetV3Small
from tensorflow.keras.applications.mobilenet_v3 import preprocess_input
import shutil
from math import floor

# ---------------- Conexión con Google Drive ----------------

DRIVE_MOUNT_POINT = Path("/content/drive")
DATASET_DIR = DRIVE_MOUNT_POINT / "MyDrive" / "CAMPIS" / "datasets" / "dataset_v5"
SUPPORTED_EXTENSIONS = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}
SEED = 42
DATASET_EVALUATION_ONLY = True

random.seed(SEED)
np.random.seed(SEED)
tf.keras.utils.set_random_seed(SEED)

drive.mount(str(DRIVE_MOUNT_POINT), force_remount=False)

if not DATASET_DIR.is_dir():
    raise FileNotFoundError(
        "No se encontró el dataset en Google Drive. Ruta esperada: "
        f"{DATASET_DIR}"
    )

# Check available GPU
print("Num GPUs Available:", len(tf.config.list_physical_devices('GPU')))

# Mostrar detalles de la GPU sin usar sintaxis exclusiva de una celda de Colab.
if shutil.which("nvidia-smi"):
    subprocess.run(["nvidia-smi"], check=False)
else:
    print("nvidia-smi no está disponible; posiblemente se está usando CPU.")

"""Carga y auditoría inicial de dataset_v5."""

# dataset_v5 debe contener directamente una carpeta por clase.
class_dirs = sorted(path for path in DATASET_DIR.iterdir() if path.is_dir())
categories = [path.name for path in class_dirs]

if len(categories) != 3:
    raise ValueError(
        f"Se esperaban exactamente 3 carpetas de clases en {DATASET_DIR}, "
        f"pero se encontraron {len(categories)}: {categories}"
    )

print("Clases detectadas:", categories)

"""EDA"""

def evaluate_dataset(dataset_dir, class_names):
    """Audita el dataset sin modificar ni mover archivos."""
    files_by_class = {}
    valid_files_by_class = defaultdict(list)
    invalid_files = []
    dimensions = Counter()
    formats = Counter()
    hashes = defaultdict(list)

    for class_name in class_names:
        class_dir = dataset_dir / class_name
        image_files = sorted(
            path for path in class_dir.iterdir()
            if path.is_file() and path.suffix.lower() in SUPPORTED_EXTENSIONS
        )
        files_by_class[class_name] = image_files

        for image_path in image_files:
            try:
                with Image.open(image_path) as image:
                    image.verify()
                with Image.open(image_path) as image:
                    dimensions[image.size] += 1
                    formats[(image.format or image_path.suffix).upper()] += 1

                digest = hashlib.sha256(image_path.read_bytes()).hexdigest()
                hashes[digest].append(image_path)
                valid_files_by_class[class_name].append(image_path)
            except (UnidentifiedImageError, OSError, ValueError) as error:
                invalid_files.append((image_path, str(error)))

    counts = {name: len(valid_files_by_class[name]) for name in class_names}
    duplicate_groups = [paths for paths in hashes.values() if len(paths) > 1]
    total = sum(counts.values())
    if total == 0:
        raise ValueError(
            "No se encontraron imágenes compatibles. Extensiones admitidas: "
            f"{sorted(SUPPORTED_EXTENSIONS)}"
        )

    smallest = min(counts.values(), default=0)
    largest = max(counts.values(), default=0)
    imbalance_ratio = largest / smallest if smallest else float("inf")

    print("\n=== AUDITORÍA DEL DATASET ===")
    print(f"Ruta: {dataset_dir}")
    print(f"Total de imágenes válidas: {total}")
    for name, count in counts.items():
        percentage = (100 * count / total) if total else 0
        print(f"  {name}: {count} ({percentage:.2f}%)")
    print(f"Relación clase mayor/menor: {imbalance_ratio:.2f}")
    print(f"Imágenes ilegibles: {len(invalid_files)}")
    print(f"Grupos de duplicados exactos: {len(duplicate_groups)}")
    print("Formatos:", dict(formats))
    print("Dimensiones más frecuentes:", dimensions.most_common(10))

    if invalid_files:
        print("\nArchivos ilegibles:")
        for path, error in invalid_files[:20]:
            print(f"  {path}: {error}")

    if duplicate_groups:
        print("\nPrimeros grupos de duplicados exactos:")
        for group in duplicate_groups[:10]:
            print("  " + " | ".join(str(path.relative_to(dataset_dir)) for path in group))

    return counts, valid_files_by_class, invalid_files, duplicate_groups


def plot_data_distribution(counts):
    fig, axes = plt.subplots(1, 2, figsize=(12, 5))
    labels = list(counts)
    values = list(counts.values())

    axes[0].pie(values, labels=labels, autopct="%1.1f%%", startangle=140)
    axes[0].set_title("Distribución por clase")
    axes[1].bar(labels, values)
    axes[1].set_ylabel("Número de imágenes válidas")
    axes[1].set_title("Cantidad de imágenes por clase")
    axes[1].tick_params(axis="x", rotation=20)
    plt.tight_layout()
    plt.show()


def show_sample_images(valid_files_by_class, samples_per_class=5):
    rng = random.Random(SEED)
    rows = len(categories)
    fig, axes = plt.subplots(rows, samples_per_class, figsize=(15, 3 * rows), squeeze=False)

    for row, category in enumerate(categories):
        candidates = valid_files_by_class[category]
        selected = rng.sample(candidates, min(samples_per_class, len(candidates)))
        for column in range(samples_per_class):
            ax = axes[row, column]
            ax.axis("off")
            if column < len(selected):
                with Image.open(selected[column]) as image:
                    ax.imshow(image.convert("RGB"))
                ax.set_title(category)

    plt.tight_layout()
    plt.show()


dataset_counts, valid_files_by_class, invalid_files, duplicate_groups = evaluate_dataset(
    DATASET_DIR, categories
)
plot_data_distribution(dataset_counts)
show_sample_images(valid_files_by_class)

if DATASET_EVALUATION_ONLY:
    print(
        "\nAuditoría terminada. El split y el entrenamiento permanecen "
        "desactivados para no modificar el dataset antes de revisar estos resultados."
    )
    raise SystemExit(0)

#------------Mover las carpetas a train,val,tes (70%,15%,15%)----------------

# Config
base_dir = "/content/drive/MyDrive/CAMPIS/datasets/dataset_v4"
classes = ["early_blight", "healthy", "late_blight"]
splits = ["train", "val", "test"]
split_ratios = [0.7, 0.15, 0.15]

# Crear carpetas de destino
for split in splits:
    for cls in classes:
        split_path = os.path.join(base_dir, split, cls)
        os.makedirs(split_path, exist_ok=True)

# Distribuir imágenes
for cls in classes:
    class_dir = os.path.join(base_dir, cls)
    images = os.listdir(class_dir)
    random.shuffle(images)

    total = len(images)
    train_end = floor(split_ratios[0] * total)
    val_end = train_end + floor(split_ratios[1] * total)

    split_images = {
        "train": images[:train_end],
        "val": images[train_end:val_end],
        "test": images[val_end:]
    }

    for split in splits:
        for img_name in split_images[split]:
            src = os.path.join(class_dir, img_name)
            dst = os.path.join(base_dir, split, cls, img_name)
            shutil.move(src, dst)

    print(f"Clase {cls}: {total} imágenes distribuidas.")

"""Data preparation and Augmentation"""

# Image settings
IMG_SIZE = (224, 224)  # Recommended for MobileNetV2
BATCH_SIZE = 32

# Ensure correct class order based on test_generator.class_indices
def get_class_names(generator):
    return [k for k, v in sorted(generator.class_indices.items(), key=lambda item: item[1])]

#----------------SET UP DEl BALANCE DE CLASES CON DATA AUMENGTATION-------------
# Paths
train_dir = "/content/drive/MyDrive/CAMPIS/datasets/dataset_v4/train"
output_dir = "/content/drive/MyDrive/CAMPIS/datasets/dataset_v4/train_augmented"
os.makedirs(output_dir, exist_ok=True)

TARGET_COUNT = 2000

# Clases
categories = ["early_blight", "healthy", "late_blight"]

# Image settings
IMG_SIZE = (224, 224)

#----------------MODELO DE DATA AUMENGTATION-------------

datagen = ImageDataGenerator(
    rotation_range=15,
    width_shift_range=0.1,
    height_shift_range=0.1,
    zoom_range=0.1,
    horizontal_flip=True,
    brightness_range=(0.8, 1.2),
    fill_mode='nearest'
)

def augment_class_images(input_dir, output_class_dir, target_count):
    os.makedirs(output_class_dir, exist_ok=True)
    images = os.listdir(input_dir)
    current_count = len(images)

    # Copiar imágenes originales
    for img_name in images:
        src = os.path.join(input_dir, img_name)
        dst = os.path.join(output_class_dir, img_name)
        shutil.copy2(src, dst)

    if current_count >= target_count:
        print(f"{output_class_dir} ya tiene suficientes imágenes.")
        return

    print(f"Augmentando {output_class_dir} de {current_count} a {target_count} imágenes...")
    generated = 0
    while current_count + generated < target_count:
        img_name = random.choice(images)
        img_path = os.path.join(input_dir, img_name)

        img = load_img(img_path, target_size=IMG_SIZE)
        x = img_to_array(img)
        x = x.reshape((1,) + x.shape)

        for batch in datagen.flow(x, batch_size=1):
            new_img_name = f"aug_{generated}_{img_name}"
            save_img(os.path.join(output_class_dir, new_img_name), batch[0])
            generated += 1
            break  # Genera una sola imagen por iteración

    print(f"Generadas {generated} imágenes para {output_class_dir}")

#----------APLICAR MODELO DE DATA AUMENGTATION------------------

# Ejecutar para cada clase
for cat in categories:
    input_class_dir = os.path.join(train_dir, cat)
    output_class_dir = os.path.join(output_dir, cat)
    augment_class_images(input_class_dir, output_class_dir, TARGET_COUNT)

#--------------------Contamos imgagenes----------------------
def count_images_in_folders(base_path, class_names):
    counts = {}
    total = 0
    for cls in class_names:
        class_path = os.path.join(base_path, cls)
        if not os.path.exists(class_path):
            print(f"⚠️  No existe: {class_path}")
            continue
        num_images = len([f for f in os.listdir(class_path) if f.lower().endswith(('.png', '.jpg', '.jpeg'))])
        counts[cls] = num_images
        total += num_images
    return counts, total

# Configura aquí
augmented_dir = "/content/drive/MyDrive/CAMPIS/datasets/dataset_v4/train_augmented"
categories = ["early_blight", "healthy", "late_blight"]

# Contar y mostrar
counts, total_images = count_images_in_folders(augmented_dir, categories)

print("\n Cantidad de imágenes por clase:")
for cls, count in counts.items():
    print(f"  {cls}: {count} imágenes")

print(f"\n Total de imágenes: {total_images}")

"""Loading the model
* MobileNetV3 architecture
* 1 dropout
* Normalization
* 3 dense layers
* 17 epochs
* 30% Unfrozen model
"""

# ---------------- Variables para el entrenamiento y validation ---------------
# Configuración de rutas
base_dir = "/content/drive/MyDrive/CAMPIS/datasets/dataset_v4"
train_aug_dir = os.path.join(base_dir, "train_augmented")
val_dir = os.path.join(base_dir, "val")

# Parámetros
IMG_SIZE = (224, 224)
BATCH_SIZE = 32
categories = ["early_blight", "healthy", "late_blight"]

# Usamos el mismo preprocessing que MobileNetV3Small
train_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)
val_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)

train_generator = train_datagen.flow_from_directory(
    train_aug_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

val_generator = val_datagen.flow_from_directory(
    val_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical'
)

# ---------------- Calcular class weights ----------------

# Obtener etiquetas de entrenamiento
labels = train_generator.classes
class_weights = compute_class_weight(
    class_weight='balanced',
    classes=np.unique(labels),
    y=labels
)
class_weights = dict(enumerate(class_weights))

print("Class weights:", class_weights)

from tensorflow.keras.applications import MobileNetV3Small
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import GlobalAveragePooling2D, Dense, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.callbacks import ReduceLROnPlateau, EarlyStopping

# ---------------- Modelo base ----------------

base_model = MobileNetV3Small(
    input_shape=IMG_SIZE + (3,),
    include_top=False,
    weights='imagenet'
)
base_model.trainable = False  # Congelar pesos para transfer learning

# ---------------- Clasificador personalizado ----------------

model = Sequential([
    base_model,
    GlobalAveragePooling2D(),
    Dense(256, activation='relu'),
    Dropout(0.3),
    Dense(128, activation='relu'),
    Dropout(0.3),
    Dense(3, activation='softmax')  # 3 clases
])

model.compile(
    optimizer=Adam(learning_rate=1e-5),
    loss='categorical_crossentropy',
    metrics=['accuracy']
)

# ---------------- Callbacks ----------------

callbacks = [
    ReduceLROnPlateau(monitor='val_loss', factor=0.5, patience=3, verbose=1),
    EarlyStopping(monitor='val_loss', patience=6, restore_best_weights=True, verbose=1)
]

# ---------------- Entrenamiento ----------------

history = model.fit(
    train_generator,
    validation_data=val_generator,
    epochs=20,
    class_weight=class_weights,
    callbacks=callbacks
)

"""#Evaluación del modelo"""

# Crear generador para el set de prueba
test_dir = "/content/drive/MyDrive/CAMPIS/datasets/dataset_v4/test"

test_datagen = ImageDataGenerator(preprocessing_function=preprocess_input)

test_generator = test_datagen.flow_from_directory(
    test_dir,
    target_size=IMG_SIZE,
    batch_size=BATCH_SIZE,
    class_mode='categorical',
    shuffle=False  # Muy importante para que las etiquetas coincidan con las predicciones
)

"""Precision. Recall, F1 score, confusion matrix, Train and validation loss and accuracy curves."""

import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import classification_report, confusion_matrix

# === EVALUATION BLOCK ===

# Evaluate on test data
y_true = test_generator.classes
y_pred_probs = model.predict(test_generator)
y_pred = np.argmax(y_pred_probs, axis=1)

# Classification Report
print("Classification Report:")
print(classification_report(y_true, y_pred, target_names=categories))

# Confusion Matrix
class_names = get_class_names(test_generator)

conf_matrix = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(conf_matrix, annot=True, fmt='d', cmap='Blues',
            xticklabels=class_names, yticklabels=class_names)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()

# Plot loss and accuracy curves
fig, ax = plt.subplots(1, 2, figsize=(12, 5))
ax[0].plot(history.history['loss'], label='Train Loss')
ax[0].plot(history.history['val_loss'], label='Validation Loss')
ax[0].set_title("Loss Curve")
ax[0].set_xlabel("Epochs")
ax[0].set_ylabel("Loss")
ax[0].legend()

ax[1].plot(history.history['accuracy'], label='Train Accuracy')
ax[1].plot(history.history['val_accuracy'], label='Validation Accuracy')
ax[1].set_title("Accuracy Curve")
ax[1].set_xlabel("Epochs")
ax[1].set_ylabel("Accuracy")
ax[1].legend()
plt.show()

# Print class label indices
print("Class indices:", train_generator.class_indices)

# === NEW BLOCK: VISUALIZE MISCLASSIFIED IMAGES ===

# Get image file paths from the test generator
misclassified_indices = np.where(y_pred != y_true)[0]
filepaths = np.array(test_generator.filepaths)

# Plot a few misclassified images
num_to_show = min(12, len(misclassified_indices))
plt.figure(figsize=(15, 10))

for i, idx in enumerate(misclassified_indices[:num_to_show]):
    img_path = filepaths[idx]
    img = plt.imread(img_path)

    true_label = class_names[y_true[idx]]
    pred_label = class_names[y_pred[idx]]
    confidence = np.max(y_pred_probs[idx])

    plt.subplot(3, 4, i + 1)
    plt.imshow(img)
    plt.axis('off')
    plt.title(f"Pred: {pred_label}\nTrue: {true_label}\nConf: {confidence:.2f}", color='red')

plt.tight_layout()
plt.suptitle("Misclassified Samples", fontsize=16)
plt.subplots_adjust(top=0.88)
plt.show()

"""Saving the model"""

# Save full model in new Keras format
model.save("/content/drive/MyDrive/CAMPIS/modelos/model_iteracion5_1.keras")

print("✅ Model saved in .keras format.")

"""tensor.lite saving"""

import tensorflow as tf

# Optional: mount Google Drive (if not done yet)
from google.colab import drive
drive.mount('/content/drive')

# 🔁 Convert to TFLite with optimization
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]  # Optional but recommended
tflite_model = converter.convert()

# 💾 Save to Google Drive
tflite_path = "/content/drive/MyDrive/CAMPIS/modelos/model_iteracion5_1.tflite"

with open(tflite_path, "wb") as f:
    f.write(tflite_model)

print(f"✅ TFLite model saved to: {tflite_path}")

"""Real images test"""

# STEP 1: Mount Google Drive (if your model is stored there)
from google.colab import drive
drive.mount('/content/drive')

# STEP 2: Import necessary libraries
import numpy as np
import requests
from PIL import Image
from io import BytesIO
import matplotlib.pyplot as plt
from tensorflow.keras.models import load_model
import os
from tensorflow.keras.applications.mobilenet_v3 import preprocess_input

# STEP 3: Load your trained model (adjust path as needed)
model_path = '/content/drive/MyDrive/CAMPIS/modelos/model_iteracion5_1.keras'  # <-- Replace with your model path
model = load_model(model_path)

# STEP 4: Define the class names (adjust based on your model)
class_names = ['early_blight', 'healthy', 'late_blight']  # <-- Replace with your actual class names

def preprocess_image(image_path, target_size=(224, 224)):
    img = Image.open(image_path).convert('RGB')
    img = img.resize(target_size)

    img_array = np.array(img)
    img_array = preprocess_input(img_array)  # Apply correct preprocessing
    img_array = np.expand_dims(img_array, axis=0)

    return img_array, img

# STEP 6: Predict on all images in the folder
image_folder = '/content/IMAGES'  # Assuming you uploaded "images/" directly into Colab
image_files = [f for f in os.listdir(image_folder) if f.lower().endswith(('.png', '.jpg', '.jpeg'))]

for image_file in image_files:
    image_path = os.path.join(image_folder, image_file)
    img_array, original_img = preprocess_image(image_path)

    prediction = model.predict(img_array)
    predicted_idx = np.argmax(prediction)
    predicted_class = class_names[predicted_idx]

    # Show image with prediction
    plt.imshow(original_img)
    plt.title(f'{image_file}\nPrediction: {predicted_class}')
    plt.axis('off')
    plt.show()

    print("Prediction probabilities:")
    for i, class_name in enumerate(class_names):
        print(f"  {class_name}: {prediction[0][i]*100:.2f}%")
    print("-" * 40)

from google.colab import drive
drive.mount('/content/drive')

# Update this to the path of your .tflite in Drive:
tflite_model_path = '/content/drive/MyDrive/CAMPIS/modelos/Iteracion 4/model_iteracion4_2.keras'

"""Tensorflow lite"""

import tensorflow as tf
interpreter = tf.lite.Interpreter(model_path=tflite_model_path)
interpreter.allocate_tensors()
input_details  = interpreter.get_input_details()
output_details = interpreter.get_output_details()

# 2) Define your preprocessing (match input_details shape & dtype)
import numpy as np
from PIL import Image

def preprocess_image(image_path):
    H, W = input_details[0]['shape'][1:3]
    img = Image.open(image_path).convert('RGB').resize((W, H))
    arr = np.array(img)

    # if model expects float input in [0,1]:
    if np.issubdtype(input_details[0]['dtype'], np.floating):
        arr = arr.astype(np.float32) / 255.0
    else:
        # e.g. uint8
        arr = arr.astype(input_details[0]['dtype'])

    return np.expand_dims(arr, axis=0), img

# 3) Upload images via Colab’s widget
from google.colab import files
uploaded = files.upload()  # opens file picker

# 4) Loop through uploaded images and do inference
import matplotlib.pyplot as plt
class_names = ['early_blight', 'healthy', 'late_blight']  # replace with your labels

for filename in uploaded.keys():
    img_array, original_img = preprocess_image(filename)

    # set input tensor & invoke
    interpreter.set_tensor(input_details[0]['index'], img_array)
    interpreter.invoke()
    output_data = interpreter.get_tensor(output_details[0]['index'])[0]  # (num_classes,)

    # interpret
    idx  = np.argmax(output_data)
    pred = class_names[idx]

    # display
    plt.imshow(original_img)
    plt.title(f'{filename}\nPrediction: {pred}')
    plt.axis('off')
    plt.show()

    print("Prediction probabilities:")
    for i, name in enumerate(class_names):
        print(f"  {name}: {output_data[i]*100:.2f}%")
    print("-"*40)
